{% set version = "2.1.6" %}

package:
  name: celiagg
  version: {{ version }}

source:
  fn: celiagg-{{ version }}.tar.gz
  url: https://github.com/celiagg/celiagg/archive/{{ version }}.tar.gz
  sha256: 4e9198c756642e8a270f7bf08bef65dfe8175afe79ea8fc8e6deb4e13cc502df

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv --disable-pip-version-check

requirements:
  build:
    - pkg-config  # [not win]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make  # [unix]
  host:
    - python
    - pip
    - setuptools
    - numpy
    - cython
    - freetype  # [not win]
    # Needs zlib development files to find freetype with pkg-config
    - zlib      # [not win]
  run:
    - python

test:
  imports:
    - celiagg

about:
  home: https://github.com/celiagg/celiagg
  license: MIT
  license_file: LICENSE
  summary: Anti-Grain Geometry 2.4 for Python with Cython

  description: |
    celiagg is a Cython wrapper for the popular Anti-Grain Geometry 2D vector
    graphics library.
  dev_url: https://github.com/celiagg/celiagg

extra:
  recipe-maintainers:
    - jwiggins
    - hmaarrfk
