{% set version = "2.1.0" %}

package:
  name: celiagg
  version: {{ version }}

source:
  fn: celiagg-{{ version }}.tar.gz
  url: https://github.com/celiagg/celiagg/archive/{{ version }}.tar.gz
  sha256: cbce1e8f8b8c9976c1dc8d28b320485922d0c869653326b231bc4063d6e245b3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv --disable-pip-version-check

requirements:
  build:
    - pkg-config  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - numpy
    - cython
    - freetype
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - freetype

test:
  imports:
    - celiagg

about:
  home: https://github.com/celiagg/celiagg
  license: MIT
  license_file: LICENSE
  summary: Anti-Grain Geometry 2.4 for Python with Cython

  description: |
    celiagg is a Cython wrapper for the popular Anti-Grain Geometry 2D vector
    graphics library.
  dev_url: https://github.com/celiagg/celiagg

extra:
  recipe-maintainers:
    - jwiggins
    - hmaarrfk
