{% set version = "2.1.2" %}

package:
  name: celiagg
  version: {{ version }}

source:
  fn: celiagg-{{ version }}.tar.gz
  url: https://github.com/celiagg/celiagg/archive/{{ version }}.tar.gz
  sha256: 22082fe071d5990e139701dabb5c373a4b9e788a67b7f060881713b4d37f3aee

build:
  number: 3
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv --disable-pip-version-check

requirements:
  build:
    - pkg-config  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - numpy
    - cython
    - freetype  # [not win]
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - celiagg

about:
  home: https://github.com/celiagg/celiagg
  license: MIT
  license_file: LICENSE
  summary: Anti-Grain Geometry 2.4 for Python with Cython

  description: |
    celiagg is a Cython wrapper for the popular Anti-Grain Geometry 2D vector
    graphics library.
  dev_url: https://github.com/celiagg/celiagg

extra:
  recipe-maintainers:
    - jwiggins
    - hmaarrfk
